### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by Kriesse** [upfrontug/upfrontug.github.io#2]
How about using SCSS? Any objections?

If not, who can add it / make it work?

**Comment by rmehner** [comment]
Problems we had at a different github-page working with SCSS:
- people need the tools installed (people seem to like CodeKit for that, but that's not free)
- we did have some merge conflicts, when two people edit the SCSS and the resulting CSS changes and is minified. When all is in one line you'll definitely have conflicts.

Apart from that, no objections.

**Comment by Kriesse** [comment]
For the merge conflicts: I use it in several projects, and as long as no one touches the CSS output, we never had any conflicts. I think the CSS should actually be ignored by git.

For the tools: What exactly is needed here? What do I use? Not sure I understand :cactus: (sorry, i just discovered these emoticons wtf haha)

**Comment by rmehner** [comment]
On 25.10.2012, at 12:22, Kristina Schneider notifications@github.com wrote:

> For the merge conflicts: I use it in several projects, and as long as no one touches the CSS output, we never had any conflicts. I think the CSS should actually be ignored by git.

Interesting, we already had that at a different project. Granted, the output CSS was minified to one single line which raises the chance for merge conflicts. If we don't do that, we shouldn't
run into this problem.

> For the tools: What exactly is needed here? What do I use? Not sure I understand  (sorry, i just discovered these emoticons wtf haha)

CodeKit or something that processes the SCSS to normal CSS as GitHub pages does not do that automatically or on deploy (like it happens for example with typical Rails projects). That's also the
reason why we can't ignore the CSS, because if we're ignoring it, it's not going to be pushed to the gh-pages and therefore does not exist on the page.

But I guess when we don't minify the CSS it's okay to just check the CSS in and we're fine.

Hope that's easier to understand, if not just ask again.
